<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PigeonPea.Map.Export\PigeonPea.Map.Export.csproj" />
    <ProjectReference Include="..\PigeonPea.Plugin.Map.MBTiles\PigeonPea.Plugin.Map.MBTiles.csproj" />
    <ProjectReference Include="..\PigeonPea.Map.Encoding\PigeonPea.Map.Encoding.csproj" />
    <ProjectReference Include="..\PigeonPea.Map.Contracts\PigeonPea.Map.Contracts.csproj" />
    <ProjectReference Include="..\PigeonPea.Plugin.Map.FMG\PigeonPea.Plugin.Map.FMG.csproj" />
    <ProjectReference Include="..\PigeonPea.Map.Core\PigeonPea.Map.Core.csproj" />
  </ItemGroup>

</Project>
