using PigeonPea.Contracts.Plugin;
using PigeonPea.Contracts.Plugin.Attributes;
using PigeonPea.Contracts.Resource.Services;

namespace PigeonPea.Resource.Contracts.Services.Proxy;

/// <summary>
/// Proxy implementation of IService that delegates to the plugin registry.
/// The actual implementation is generated by the proxy source generator.
/// </summary>
[RealizeService(typeof(IService))]
public partial class Service : IService
{
    private readonly IRegistry _registry;

    public Service(IRegistry registry)
    {
        _registry = registry ?? throw new ArgumentNullException(nameof(registry));
    }
}
