<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\game-essential\contracts\src\PigeonPea.Game.Contracts\PigeonPea.Game.Contracts.csproj" />
    <ProjectReference Include="..\..\..\game-essential\core\src\PigeonPea.Shared.ECS\PigeonPea.Shared.ECS.csproj" />
    <ProjectReference Include="..\..\..\app-essential\core\src\PigeonPea.Contracts\PigeonPea.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Arch" Version="2.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
