<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <IsPackable>false</IsPackable>
    <RootNamespace>PigeonPea.Benchmarks</RootNamespace>
    <AssemblyName>PigeonPea.Benchmarks</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../game-essential/core/src/PigeonPea.Shared/PigeonPea.Shared.csproj" />
    <ProjectReference Include="../game-essential/core/src/PigeonPea.Rendering.Contracts/PigeonPea.Rendering.Contracts.csproj" />
    <ProjectReference Include="../../projects/dungeon/dotnet/console-app/plugins/PigeonPea.Plugins.Rendering.Terminal.ANSI/PigeonPea.Plugins.Rendering.Terminal.ANSI.csproj" />
    <ProjectReference Include="../../projects/dungeon/dotnet/console-app/plugins/PigeonPea.Plugin.Rendering.Terminal.Braille/PigeonPea.Plugin.Rendering.Terminal.Braille.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="FantasyMapGenerator.Benchmarks\**\*.cs" />
  </ItemGroup>

</Project>
