<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>bin/$(Configuration)/$(TargetFramework)/PigeonPea.Dungeon.Contracts.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\app-essential\core\src\PigeonPea.Contracts\PigeonPea.Contracts.csproj" />
    <ProjectReference Include="..\PigeonPea.Rendering.Contracts\PigeonPea.Rendering.Contracts.csproj" />
    <ProjectReference Include="..\PigeonPea.Overlays\PigeonPea.Overlays.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Arch" Version="2.0.0" />
  </ItemGroup>
</Project>
