# Taskfile.yml
# Task runner configuration for pigeon-pea project
# Install Task: https://taskfile.dev/installation/
# Usage: task <task-name> or just `task` to see available tasks

version: '3'

tasks:
  skills:validate:
    desc: Validate all agent skills
    cmds:
      - python scripts/validate_skills.py

  agents:validate:
    desc: Validate all agent manifests
    cmds:
      - python scripts/validate_agents.py

  registry:generate:
    desc: Generate AGENTS.md registry from manifests
    cmds:
      - python scripts/generate_registry.py

  check:
    desc: Run all validations
    deps:
      - skills:validate
      - agents:validate
      - registry:generate

  dotnet:build:
    desc: Build .NET solution
    dir: ./dotnet
    cmds:
      - dotnet build PigeonPea.sln

  dotnet:test:
    desc: Run .NET tests
    dir: ./dotnet
    cmds:
      - dotnet test PigeonPea.sln

  dotnet:format:
    desc: Format .NET code
    dir: ./dotnet
    cmds:
      - dotnet format

  # PTY test helpers (Node.js)
  pty:install:
    desc: Install Node.js deps for PTY tests
    dir: ./tests/pty
    cmds:
      - npm ci

  pty:test:
    desc: Run PTY basic movement test
    dir: ./tests/pty
    cmds:
      - npm test

  # Developer environment helpers
  env:check-terminal:
    desc: Check terminal environment and WezTerm info (Windows)
    cmds:
      - scripts\\check-terminal.bat

  env:which-wezterm:
    desc: Locate wezterm and test imgcat (Windows)
    cmds:
      - scripts\\which-wezterm.bat

  env:test-with-env:
    desc: Run console app with kitty env vars (Windows)
    cmds:
      - scripts\\test-with-env.bat

  wezterm:launch:
    desc: Launch pinned WezTerm instance (Windows)
    cmds:
      - scripts\\launch-new-wezterm.bat

  dev:setup-pre-commit:win:
    desc: Setup pre-commit hooks (Windows PowerShell)
    cmds:
      - pwsh -File scripts/setup-pre-commit.ps1

  dev:setup-pre-commit:unix:
    desc: Setup pre-commit hooks (bash)
    cmds:
      - bash scripts/setup-pre-commit.sh

  images:create-battle:
    desc: Generate sample battle image (Pillow)
    cmds:
      - python3 scripts/create_battle_image.py

  images:create-test:
    desc: Generate 32x32 red test image (Pillow)
    cmds:
      - python3 scripts/create_test_image.py

  python:install-dev:
    desc: Install Python dev dependencies
    cmds:
      - python -m pip install -r requirements/dev.txt

  fonts:generate-svgs:
    desc: Generate 36 angle SVGs for font import
    dir: .
    cmds:
      - python3 fonts/scripts/generate_angle_svgs.py

  fonts:build:regular:
    desc: Patch Regular font with PUA angles (requires FontForge)
    dir: .
    cmds:
      - |
        if [ -z "${BASE_FONT_REGULAR}" ]; then \
          echo "Set BASE_FONT_REGULAR to Sarasa Fixed CL Regular TTF path" && exit 1; fi
      - |
        fontforge -script fonts/scripts/patch_sarasa.py \
          --base "${BASE_FONT_REGULAR}" \
          --output fonts/dist/LunarSarasaMono-Regular.ttf \
          --svg-dir fonts/src/svg/lines

  fonts:build:bold:
    desc: Patch Bold font with PUA angles (requires FontForge)
    dir: .
    cmds:
      - |
        if [ -z "${BASE_FONT_BOLD}" ]; then \
          echo "Set BASE_FONT_BOLD to Sarasa Fixed CL Bold TTF path" && exit 1; fi
      - |
        fontforge -script fonts/scripts/patch_sarasa.py \
          --base "${BASE_FONT_BOLD}" \
          --output fonts/dist/LunarSarasaMono-Bold.ttf \
          --svg-dir fonts/src/svg/lines

  fonts:build:
    desc: Build Regular and Bold patched fonts
    deps:
      - fonts:generate-svgs
      - fonts:build:regular
      - fonts:build:bold

  fonts:test:
    desc: Basic check for generated fonts
    dir: .
    cmds:
      - bash -lc "ls -l fonts/dist/*.ttf || true"

  bundle:rio:dev:
    desc: Create a dev bundle skeleton (no Rio binaries)
    dir: .
    cmds:
      - mkdir -p bundle/fonts bundle/config bundle/app
      - bash -lc "cp -f fonts/dist/*.ttf bundle/fonts/ 2>/dev/null || true"
      - |
        bash -lc 'cat > bundle/config/rio.toml <<EOF
        [fonts]
        normal = { family = "Lunar Sarasa Mono" }
        bold   = { family = "Lunar Sarasa Mono" }
        italic = { family = "Lunar Sarasa Mono" }
        EOF'

  default:
    desc: Show available tasks
    cmds:
      - task --list
