<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- Console & HUD -->
    <PackageVersion Include="Terminal.Gui" Version="2.0.0" />
    <PackageVersion Include="System.CommandLine" Version="2.0.0-rc.2.25502.107" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageVersion Include="Scrutor" Version="4.2.2" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageVersion Include="Plate.SCG.Shared.Attributes" Version="0.1.0" />
    <PackageVersion Include="Riok.Mapperly" Version="4.1.0" />


    <!-- Logging and DI -->
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.0" />


    <!-- Rendering / Primitives -->
    <PackageVersion Include="TheSadRogue.Primitives" Version="1.6.0-rc3" />

    <!-- Reactive / Fody -->
    <PackageVersion Include="ReactiveUI" Version="20.1.1" />
    <PackageVersion Include="ReactiveUI.Fody" Version="20.1.1" />
    <PackageVersion Include="Fody" Version="6.8.0" />

    <!-- Serilog -->
    <PackageVersion Include="Serilog" Version="4.2.0" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="9.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="9.0.0" />

    <!-- Maps / Tiles -->
    <PackageVersion Include="Mapsui" Version="5.0.0" />
    <PackageVersion Include="BruTile" Version="6.0.0" />
  </ItemGroup>
</Project>
