<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove(Directory.Packages.props, $(MSBuildThisFileDirectory)..))" />
  <ItemGroup>
    <!-- Avalonia / Skia / UI -->
    <PackageVersion Include="Avalonia" Version="11.2.2" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.2.2" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.2.2" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="11.2.2" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.2.2" />
    <PackageVersion Include="Avalonia.Skia" Version="11.2.2" />
    <PackageVersion Include="Avalonia.ReactiveUI" Version="11.2.2" />
    <PackageVersion Include="SkiaSharp" Version="3.116.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="3.116.1" />
    <PackageVersion Include="Plate.SCG.General.DisposePattern" Version="0.1.0" />
  </ItemGroup>
</Project>
