name: Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please fill out the information below.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README.md
        - CONTRIBUTING.md
        - AGENTS.md
        - CLAUDE.md
        - Code comments
        - API documentation
        - Agent documentation
        - Scripts documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue with Current Documentation
      description: What's wrong or missing in the current documentation?
      placeholder: The documentation is unclear about...
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation located? (file path, URL, section)
      placeholder: |
        File: README.md
        Section: Installation
        Line: 45-60
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: The documentation should explain...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Proposed Changes
      description: If you have specific text or code examples, please provide them here
      placeholder: |
        Current text: "..."
        Proposed text: "..."
      render: markdown

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How much does this documentation issue affect users?
      options:
        - Low - Minor clarification
        - Medium - Could confuse some users
        - High - Blocking or misleading
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the documentation improvement
      placeholder: Additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have reviewed the current documentation
          required: true
        - label: I am willing to submit a PR to fix this (optional)
          required: false
