<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>13</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>Yokan.SCG.DI.ConstructorInjection</AssemblyName>
    <RootNamespace>Yokan.SCG.DI.ConstructorInjection</RootNamespace>
    <IsRoslynAnalyzer>true</IsRoslynAnalyzer>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <DevelopmentDependency>true</DevelopmentDependency>
    <IsRoslynComponent>true</IsRoslynComponent>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.10.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" PrivateAssets="all" />
    <PackageReference Include="Plate.SCG.Shared.Abstractions" Version="0.1.0" />
  </ItemGroup>

</Project>
