// Copyright (c) GiantCroissant. All rights reserved.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Yokan.SCG.DI.ConstructorInjection;

using Plate.SCG.Shared.Abstractions;

[Generator(LanguageNames.CSharp)]
public sealed class SourceGenerator : IIncrementalGenerator
{
    private const string ConstructorInjection = "ConstructorInjection";
    private const string ConstructorInjectionAttribute = "ConstructorInjectionAttribute";
    private const string AttributeName = "ResolveInConstructor";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (syntaxNode, cancellationToken) =>
                    Utility.PredicateAsync(syntaxNode, ConstructorInjection, ConstructorInjectionAttribute, cancellationToken),
                Utility.TransformAsync)
            .Where(static typeSymbol => typeSymbol is not null)
            .Collect();

        context.RegisterSourceOutput(typeSymbols, GenerateCode!);
    }

    private static void GenerateCode(
        SourceProductionContext context,
        ImmutableArray<ITypeSymbol> typeSymbols)
    {
        if (typeSymbols.IsDefaultOrEmpty)
        {
            return;
        }

        var executingAssemblyName = Assembly.GetExecutingAssembly().GetName();
        foreach (var typeSymbol in typeSymbols)
        {
            var ns = typeSymbol.ContainingNamespace.ToDisplayString();
            var fileName = $"{ns}.{typeSymbol.Name}.DI.ConstructorInjection.g.cs";
            context.AddSource(fileName, GenerateCode(executingAssemblyName, fileName, typeSymbol));
        }
    }

    private static string GenerateCode(
        AssemblyName executingAssemblyName,
        string fileName,
        ITypeSymbol typeSymbol)
    {
        var assemblyName = $"{executingAssemblyName.Name}.{nameof(SourceGenerator)}";
        var assemblyVersion = $"{executingAssemblyName.Version}";
        var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
        var typeDeclarationLine = Utility.CreateTypeDeclarationLine(typeSymbol);
        var typeName = typeSymbol.Name;
        var codeGenAttributes = Utility.CreateCodeGenAttributes(assemblyName, assemblyVersion);
        var attributedSymbols = Utility.GetAttributedSymbols(typeSymbol, AttributeName);
        var indentedAttributes = Utility.Indent(codeGenAttributes, 4);
        var parameters = CreateParams(attributedSymbols, 8);
        var assignment = CreateAssignment(attributedSymbols, 8);

        return
$$"""
// <auto-generated />
// {fileName}

#nullable enable

namespace {namespaceName};

{typeDeclarationLine}
{{
{indentedAttributes}
    public {typeName}({parameters})
    {{
        ConstructorBegin();

        {assignment}

        ConstructorEnd();
    }}

{indentedAttributes}
    partial void ConstructorBegin();

{indentedAttributes}
    partial void ConstructorEnd();
}}
""";
    }

    private static string CreateParams(List<ISymbol> symbols, int indent = 4)
    {
        var indentString = new string(' ', indent);
        var paramStrings = symbols
            .Select(symbol => (IFieldSymbol) symbol)
            .Select(fieldSymbol =>
            {
                var strippedUnderscore = fieldSymbol.Name.TrimStart('_');
                return $"{indentString}{fieldSymbol.Type.ToDisplayString()} {strippedUnderscore},";
            })
            .ToList();

        var adjustedParamStrings = string
            .Join(Environment.NewLine, paramStrings)
            .TrimEnd(',');

        return
$$"""

{adjustedParamStrings}
""";
    }

    private static string CreateAssignment(List<ISymbol> symbols, int indent = 4)
    {
        var indentString = new string(' ', indent);
        var assignmentStrings = symbols
            .Select(symbol =>
            {
                var strippedUnderscore = symbol.Name.TrimStart('_');
                return $"{indentString}{symbol.Name} = {strippedUnderscore};";
            })
            .ToList();

        var adjustedAssignmentStrings = string
            .Join(Environment.NewLine, assignmentStrings)
            .TrimStart(indentString.ToCharArray())
            .TrimEnd(Environment.NewLine.ToCharArray().Concat(new[] {',', ' '}).ToArray());

        return
$$"""
{adjustedAssignmentStrings}
""";
    }
}
