<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mapsui" Version="5.0.0" />
    <PackageReference Include="BruTile" Version="6.0.0" />
    <PackageReference Include="System.Reactive" Version="6.0.1" />
    <PackageReference Include="ReactiveUI" Version="20.1.1" />
    <PackageReference Include="Arch" Version="2.0.0" />
    <PackageReference Include="Plate.SCG.Shared.Attributes" Version="0.1.0" />
    <PackageReference Include="Plate.SCG.General.DisposePattern" Version="0.1.0" PrivateAssets="all" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PigeonPea.Map.Core\PigeonPea.Map.Core.csproj" />
    <ProjectReference Include="..\..\shared\PigeonPea.Shared.ECS\PigeonPea.Shared.ECS.csproj" />
    <ProjectReference Include="..\..\..\..\content-authoring\core\src\PigeonPea.Content.ECS\PigeonPea.Content.ECS.csproj" />
  </ItemGroup>
</Project>
