using System.IO.Compression;
using BruTile.MbTiles;
using PigeonPea.Map.Contracts.Providers;
using PigeonPea.Map.Contracts.Spatial;
using PigeonPea.Map.Encoding;
using SQLite;

namespace PigeonPea.Map.Export;

/// <summary>
/// Exports IMapProvider data to MBTiles format using BruTile.MbTiles (sqlite-net)
/// </summary>
public class MBTilesExporter
{
    private readonly IMapProvider _provider;
    private readonly MBTilesOptions _options;
    private readonly IVectorTileEncoder _encoder;
    private readonly IProgress<ExportProgress>? _progress;

    public MBTilesExporter(
        IMapProvider provider,
        MBTilesOptions options,
        IVectorTileEncoder encoder,
        IProgress<ExportProgress>? progress = null)
    {
        _provider = provider ?? throw new ArgumentNullException(nameof(provider));
        _options = options ?? throw new ArgumentNullException(nameof(options));
        _encoder = encoder ?? throw new ArgumentNullException(nameof(encoder));
        _progress = progress;
    }

    /// <summary>
    /// Export map data to MBTiles file using BruTile.MbTiles (sqlite-net)
    /// </summary>
    public async Task ExportAsync(string outputPath, CancellationToken ct = default)
    {
        if (File.Exists(outputPath))
        {
            File.Delete(outputPath);
        }

        using var db = new SQLiteConnection(outputPath);
        
        // Create tables
        db.CreateTable<MbTileMetadata>();
        db.CreateTable<MbTile>();

        // Write metadata
        WriteMetadata(db);

        var totalTiles = CalculateTotalTiles();
        var processedTiles = 0;

        for (int z = _options.MinZoom; z <= _options.MaxZoom; z++)
        {
            ct.ThrowIfCancellationRequested();

            await GenerateZoomLevelAsync(db, z, ct);

            var tilesInLevel = CalculateTilesForZoom(z);
            processedTiles += tilesInLevel;

            _progress?.Report(new ExportProgress(z, _options.MaxZoom, processedTiles, totalTiles));
        }

        // Create index
        // Index is created automatically by sqlite-net attributes on MbTile class
    }

    private void WriteMetadata(SQLiteConnection db)
    {
        var metadata = new[]
        {
            new MbTileMetadata { Name = "name", Value = _options.Name ?? "Generated Map" },
            new MbTileMetadata { Name = "type", Value = "baselayer" },
            new MbTileMetadata { Name = "version", Value = "1.0.0" },
            new MbTileMetadata { Name = "description", Value = _options.Description ?? $"Generated by {_provider.ProviderId}" },
            new MbTileMetadata { Name = "attribution", Value = _options.Attribution ?? "© PigeonPea" },
            new MbTileMetadata { Name = "format", Value = "pbf" },
            new MbTileMetadata { Name = "bounds", Value = FormatBounds(_options.Bounds) },
            new MbTileMetadata { Name = "center", Value = FormatCenter(_options.Bounds, _options.DefaultZoom) },
            new MbTileMetadata { Name = "minzoom", Value = _options.MinZoom.ToString() },
            new MbTileMetadata { Name = "maxzoom", Value = _options.MaxZoom.ToString() }
        };

        db.InsertAll(metadata);
    }

    private async Task GenerateZoomLevelAsync(SQLiteConnection db, int zoom, CancellationToken ct)
    {
        var tiles = CalculateTilesForZoomLevel(zoom, _options.Bounds).ToList();
        var tileBatch = new List<MbTile>();
        var batchLock = new object();

        await Parallel.ForEachAsync(tiles, new ParallelOptions 
        { 
            MaxDegreeOfParallelism = _options.MaxParallelism,
            CancellationToken = ct 
        }, async (tile, token) =>
        {
            var (z, x, y) = tile;
            var tileData = await GenerateTileAsync(z, x, y, token);

            if (tileData.Length > 0)
            {
                // MBTiles uses TMS (Y goes up from bottom).
                var tmsY = (1 << z) - 1 - y;
                
                var mbTile = new MbTile
                {
                    ZoomLevel = z,
                    TileColumn = x,
                    TileRow = tmsY, 
                    TileData = tileData
                };

                List<MbTile>? batchToWrite = null;

                lock (batchLock)
                {
                    tileBatch.Add(mbTile);
                    if (tileBatch.Count >= _options.BatchSize)
                    {
                        batchToWrite = new List<MbTile>(tileBatch);
                        tileBatch.Clear();
                    }
                }

                if (batchToWrite != null)
                {
                    db.InsertAll(batchToWrite);
                }
            }
        });

        if (tileBatch.Count > 0)
        {
            db.InsertAll(tileBatch);
        }
    }

    private async Task<byte[]> GenerateTileAsync(int z, int x, int y, CancellationToken ct)
    {
        var bounds = TileToBounds(x, y, z);

        if (!_provider.CanServe(bounds))
        {
            return Array.Empty<byte>();
        }

        var mapData = await _provider.GetMapAsync(bounds, ct);

        var features = mapData.GetFeatures(bounds, new ZoomLevel(z)).ToList();

        if (features.Count == 0)
        {
            return Array.Empty<byte>();
        }

        var vectorTile = _encoder.Encode(features, bounds, z);

        return _options.Compress ? CompressTile(vectorTile) : vectorTile;
    }

    private BoundingBox TileToBounds(int x, int y, int zoom)
    {
        var tilesPerSide = 1 << zoom;
        var tileWidth = _options.Bounds.Width / tilesPerSide;
        var tileHeight = _options.Bounds.Height / tilesPerSide;

        return new BoundingBox(
            _options.Bounds.X + (x * tileWidth),
            _options.Bounds.Y + (y * tileHeight),
            tileWidth,
            tileHeight);
    }

    private int CalculateTotalTiles()
    {
        int total = 0;
        for (int z = _options.MinZoom; z <= _options.MaxZoom; z++)
        {
            total += CalculateTilesForZoom(z);
        }
        return total;
    }

    private int CalculateTilesForZoom(int zoom)
    {
        var tilesPerSide = 1 << zoom;
        return tilesPerSide * tilesPerSide;
    }

    private IEnumerable<(int Z, int X, int Y)> CalculateTilesForZoomLevel(int zoom, BoundingBox bounds)
    {
        var tilesPerSide = 1 << zoom;

        for (int y = 0; y < tilesPerSide; y++)
        {
            for (int x = 0; x < tilesPerSide; x++)
            {
                yield return (zoom, x, y);
            }
        }
    }

    private byte[] CompressTile(byte[] data)
    {
        using var input = new MemoryStream(data);
        using var output = new MemoryStream();
        using var gzip = new GZipStream(output, CompressionLevel.Optimal);

        input.CopyTo(gzip);
        gzip.Close();

        return output.ToArray();
    }



    private string FormatBounds(BoundingBox bounds)
    {
        return $"{bounds.X},{bounds.Y},{bounds.X + bounds.Width},{bounds.Y + bounds.Height}";
    }

    private string FormatCenter(BoundingBox bounds, int zoom)
    {
        var centerX = bounds.X + bounds.Width / 2;
        var centerY = bounds.Y + bounds.Height / 2;
        return $"{centerX},{centerY},{zoom}";
    }
}
