using System;
using PigeonPea.Platform.Contracts.Recording.Services;
using PigeonPea.Platform.Contracts.Core;
using PigeonPea.Platform.Contracts.Core.Attributes;

namespace PigeonPea.Platform.Contracts.Recording.Services.Proxy;

/// <summary>
/// Proxy implementation of IService that delegates to the plugin registry.
/// The actual implementation is generated by the proxy source generator.
/// </summary>
[RealizeService(typeof(IService))]
public partial class Service : IService
{
    private readonly IRegistry _registry;

    public Service(IRegistry registry)
    {
        _registry = registry ?? throw new ArgumentNullException(nameof(registry));
    }
}
