using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Plate.SCG.General.AutoToString;

using Plate.SCG.Shared.Abstractions;

[Generator(LanguageNames.CSharp)]
public class SourceGenerator : IIncrementalGenerator
{
    private const string AutoToString = "AutoToString";
    private const string AutoToStringAttribute = "AutoToStringAttribute";
    private const string AddToString = "AddToString";
    private const string AddToStringAttribute = "AddToStringAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (syntaxNode, cancellationToken) =>
                    Utility.PredicateAsync(syntaxNode, AutoToString, AutoToStringAttribute, cancellationToken),
                Utility.TransformAsync)
            .Where(static typeSymbol => typeSymbol is not null)
            .Collect();

        context.RegisterSourceOutput(typeSymbols, GenerateCode!);
    }

    private static void GenerateCode(
        SourceProductionContext context,
        ImmutableArray<ITypeSymbol> typeSymbols)
    {
        if (typeSymbols.IsDefaultOrEmpty)
        {
            return;
        }

        var executingAssemblyName = Assembly.GetExecutingAssembly().GetName();
        foreach (var typeSymbol in typeSymbols)
        {
            var ns = typeSymbol.ContainingNamespace.ToDisplayString();
            var fileName = $"{ns}.{typeSymbol.Name}.General.AutoToString.g.cs";
            context.AddSource(fileName, GenerateCode(executingAssemblyName, fileName, typeSymbol));
        }
    }

    private static string GenerateCode(
        AssemblyName executingAssemblyName,
        string fileName,
        ITypeSymbol typeSymbol)
    {
        var assemblyName = $"{executingAssemblyName.Name}.{nameof(SourceGenerator)}";
        var assemblyVersion = $"{executingAssemblyName.Version}";
        var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
        var typeDeclarationLine = Utility.CreateTypeDeclarationLine(typeSymbol);
        var codeGenAttributes = Utility.CreateCodeGenAttributes(assemblyName, assemblyVersion);
        var indentedAttributes = Utility.Indent(codeGenAttributes, 4);

        var addToStrings = Utility.GetAttributedSymbols(typeSymbol, AddToString);
        var desc = CreateString(addToStrings, typeSymbol);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// {fileName}");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine(typeDeclarationLine);
        sb.AppendLine("{");
        sb.Append(indentedAttributes);
        sb.AppendLine("    public override string ToString()");
        sb.AppendLine("    {");
        sb.AppendLine($"        return $$\"\"\"{CreateReturnStatement(typeSymbol, desc)}\"\"\";");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string CreateReturnStatement(
        ITypeSymbol typeSymbol,
        string desc)
    {
        return $$"""
                 {typeSymbol.Name} {desc}
                 """;
    }

    private static string CreateString(
        List<ISymbol> addToStrings,
        ITypeSymbol typeSymbol)
    {
        var contentBuilder = new StringBuilder();
        var isFirst = true;
        foreach (var addToString in addToStrings)
        {
            var symbolType = addToString switch
            {
                IPropertySymbol p => p.Type,
                IFieldSymbol f => f.Type,
                _ => null
            };

            var accessor = addToString.Name;

            if (!isFirst)
            {
                contentBuilder.Append(", ");
            }

            var isNullable = symbolType?.NullableAnnotation == NullableAnnotation.Annotated || symbolType?.IsReferenceType == true;

            if (symbolType != null && IsDictionary(symbolType))
            {
                contentBuilder.Append($"{accessor} = {{{{{accessor} != null ? \"[\" + string.Join(\", \", global::System.Linq.Enumerable.Select({accessor}, kvp => kvp.Key + \"=\" + kvp.Value)) + \"]\" : \"null\"}}}}}");
            }
            else if (symbolType != null && IsCollection(symbolType))
            {
                contentBuilder.Append($"{accessor} = {{{{{accessor} != null ? \"[\" + string.Join(\", \", {accessor}) + \"]\" : \"null\"}}}}}");
            }
            else if (isNullable && symbolType?.SpecialType != SpecialType.System_String)
            {
                contentBuilder.Append($"{accessor} = {{{{{accessor} != null ? {accessor}.ToString() : \"null\"}}}}}");
            }
            else
            {
                contentBuilder.Append($"{accessor} = {{{accessor}}}");
            }

            isFirst = false;
        }

        var interpolated = contentBuilder.ToString();
        return interpolated;
    }

    private static bool IsDictionary(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedType)
        {
            return false;
        }

        foreach (var @interface in namedType.AllInterfaces)
        {
            var originalDefinition = @interface.OriginalDefinition?.ToDisplayString() ?? string.Empty;

            if (originalDefinition.Equals("System.Collections.Generic.IDictionary<TKey, TValue>", StringComparison.Ordinal) ||
                originalDefinition.Equals("System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>", StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsCollection(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol)
        {
            return true;
        }

        if (type is not INamedTypeSymbol namedType)
        {
            return false;
        }

        if (type.SpecialType == SpecialType.System_String)
        {
            return false;
        }

        foreach (var @interface in namedType.AllInterfaces)
        {
            var originalDefinition = @interface.OriginalDefinition?.ToDisplayString() ?? string.Empty;

            if (originalDefinition.Equals("System.Collections.IEnumerable", StringComparison.Ordinal) ||
                originalDefinition.Equals("System.Collections.Generic.IEnumerable<T>", StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }
}
