<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../PigeonPea.Plugin.Recording.Events/PigeonPea.Plugin.Recording.Events.csproj" />
    <ProjectReference Include="../../../../core/src/PigeonPea.Contracts/PigeonPea.Contracts.csproj" />
      <ProjectReference Include="..\..\..\contracts\src\PigeonPea.Recording.Contracts\PigeonPea.Recording.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="Moq" Version="4.20.69" />
      <ProjectReference Include="..\..\..\contracts\src\PigeonPea.Recording.Contracts\PigeonPea.Recording.Contracts.csproj" />
  </ItemGroup>

</Project>
