#!/usr/bin/env python3
"""Generate AGENTS.md registry from agent and skill manifests.

This script reads all agent YAML files and skill SKILL.md files,
extracts their metadata, and generates markdown tables in AGENTS.md.
The script preserves any manual introduction content in AGENTS.md.
"""
import sys
from pathlib import Path
from typing import Any, Dict, List

import yaml


def extract_frontmatter(skill_md_path: Path) -> Dict[str, Any]:
    """Extract YAML front-matter from SKILL.md file.

    Args:
        skill_md_path: Path to the SKILL.md file

    Returns:
        Dictionary containing the parsed front-matter

    Raises:
        ValueError: If front-matter is missing or invalid
    """
    with open(skill_md_path) as f:
        content = f.read()

    if not content.startswith("---"):
        raise ValueError(f"Missing front-matter in {skill_md_path}")

    parts = content.split("---", 2)
    if len(parts) < 3:
        raise ValueError(f"Invalid front-matter format in {skill_md_path}")

    return yaml.safe_load(parts[1])


def read_agents(agents_dir: Path) -> List[Dict[str, Any]]:
    """Read all agent YAML files from the agents directory.

    Args:
        agents_dir: Path to the .agent/agents directory

    Returns:
        List of agent dictionaries sorted by name
    """
    agents = []
    for agent_file in sorted(agents_dir.glob("*.yaml")):
        with open(agent_file) as f:
            agent = yaml.safe_load(f)
            agents.append(agent)
    return agents


def read_skills(skills_dir: Path) -> List[Dict[str, Any]]:
    """Read all skill front-matter from SKILL.md files.

    Args:
        skills_dir: Path to the .agent/skills directory

    Returns:
        List of skill dictionaries sorted by name
    """
    skills = []
    for skill_dir in sorted(skills_dir.iterdir()):
        if skill_dir.is_dir():
            skill_md = skill_dir / "SKILL.md"
            if skill_md.exists():
                try:
                    fm = extract_frontmatter(skill_md)
                    skills.append(fm)
                except (ValueError, yaml.YAMLError) as e:
                    print(f"Warning: Failed to parse {skill_md}: {e}", file=sys.stderr)
    return skills


def generate_agent_table(agents: List[Dict[str, Any]]) -> str:
    """Generate markdown table for agents.

    Args:
        agents: List of agent dictionaries

    Returns:
        Markdown table string
    """
    lines = [
        "| Name | Description | Version | Skills |",
        "|------|-------------|---------|--------|",
    ]

    for agent in agents:
        name = agent.get("name", "Unknown")
        description = agent.get("description", "No description")
        version = agent.get("version", "0.0.0")
        skills = agent.get("skills", [])
        skills_list = ", ".join(skills) if skills else "None"

        lines.append(f"| {name} | {description} | {version} | {skills_list} |")

    return "\n".join(lines)


def generate_skill_table(skills: List[Dict[str, Any]]) -> str:
    """Generate markdown table for skills.

    Args:
        skills: List of skill dictionaries

    Returns:
        Markdown table string
    """
    lines = [
        "| Name | Kind | Description | Version |",
        "|------|------|-------------|---------|",
    ]

    for skill in skills:
        name = skill.get("name", "unknown")
        kind = skill.get("kind", "unknown")
        description = skill.get("description", "No description")
        version = skill.get("version", "0.0.0")

        lines.append(f"| {name} | {kind} | {description} | {version} |")

    return "\n".join(lines)


def generate_registry_section(
    agents: List[Dict[str, Any]], skills: List[Dict[str, Any]]
) -> str:
    """Generate the complete registry section.

    Args:
        agents: List of agent dictionaries
        skills: List of skill dictionaries

    Returns:
        Complete registry section as markdown
    """
    registry = []
    registry.append("## Agent Infrastructure Registry")
    registry.append("")
    registry.append("<!-- Auto-generated by scripts/generate_registry.py -->")
    registry.append("<!-- Do not edit this section manually -->")
    registry.append("")
    registry.append("### Agents")
    registry.append("")
    registry.append(generate_agent_table(agents))
    registry.append("")
    registry.append("### Skills")
    registry.append("")
    registry.append(generate_skill_table(skills))
    registry.append("")

    return "\n".join(registry)


def update_agents_md(agents_md_path: Path, registry_section: str) -> None:
    """Update AGENTS.md with the generated registry section.

    This function preserves any manual introduction content before
    the registry section and replaces only the registry section.

    Args:
        agents_md_path: Path to AGENTS.md
        registry_section: The generated registry section
    """
    if agents_md_path.exists():
        with open(agents_md_path) as f:
            existing = f.read()

        # Find the registry section marker
        marker = "## Agent Infrastructure Registry"
        if marker in existing:
            # Split at the marker and keep only the intro
            intro_part = existing.split(marker, 1)[0].rstrip()
            final_content = intro_part + "\n\n" + registry_section
        else:
            # No existing registry, append to end
            final_content = existing.rstrip() + "\n\n" + registry_section
    else:
        # No existing file, create with just the registry
        final_content = registry_section

    with open(agents_md_path, "w") as f:
        f.write(final_content)


def main() -> int:
    """Main entry point for the script.

    Returns:
        Exit code (0 for success, 1 for error)
    """
    # Define paths
    repo_root = Path(__file__).parent.parent
    agents_dir = repo_root / ".agent" / "agents"
    skills_dir = repo_root / ".agent" / "skills"
    agents_md = repo_root / "AGENTS.md"

    # Validate directories exist
    if not agents_dir.exists():
        print(f"Error: Agents directory not found: {agents_dir}", file=sys.stderr)
        return 1

    if not skills_dir.exists():
        print(f"Error: Skills directory not found: {skills_dir}", file=sys.stderr)
        return 1

    # Read agents and skills
    try:
        agents = read_agents(agents_dir)
        skills = read_skills(skills_dir)
    except Exception as e:
        print(f"Error reading manifests: {e}", file=sys.stderr)
        return 1

    # Generate registry section
    registry_section = generate_registry_section(agents, skills)

    # Update AGENTS.md
    try:
        update_agents_md(agents_md, registry_section)
        print(f"✓ Successfully updated {agents_md}")
        print(f"  - {len(agents)} agents")
        print(f"  - {len(skills)} skills")
    except Exception as e:
        print(f"Error updating AGENTS.md: {e}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
