<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);CA1716;CA1711;CA1814</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TheSadRogue.Primitives" Version="1.6.0-rc3" />
    <PackageReference Include="SkiaSharp" Version="2.88.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\contracts\PigeonPea.Rendering.Contracts\PigeonPea.Rendering.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Primitives\CurveSmoothing.cs" />
  </ItemGroup>
</Project>
