using System;
using System.Collections.Generic;
using System.Linq;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using PigeonPea.SourceGenerators.Proxy;
using Xunit;

namespace PigeonPea.PluginSystem.Tests;

public class ProxyGeneratorTests
{
    [Fact]
    public void ProxyGeneratorGeneratesProxyAndDIExtensionsForRealizeService()
    {
        const string source = @"using System;\nusing System.Collections.Generic;\nusing PigeonPea.Contracts.Plugin;\nusing PigeonPea.Contracts.Plugin.Attributes;\n\nnamespace PigeonPea.Contracts.Plugin\n{\n    public enum SelectionMode { One, HighestPriority, All }\n\n    public interface IRegistry\n    {\n        TService Get<TService>(SelectionMode mode = SelectionMode.HighestPriority) where TService : class;\n        IEnumerable<TService> GetAll<TService>() where TService : class;\n    }\n}\n\nnamespace PigeonPea.Contracts.Plugin.Attributes\n{\n    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]\n    public sealed class RealizeServiceAttribute : Attribute\n    {\n        public Type ServiceType { get; }\n        public RealizeServiceAttribute(Type serviceType) => ServiceType = serviceType;\n    }\n\n    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]\n    public sealed class SelectionStrategyAttribute : Attribute\n    {\n        public SelectionMode Mode { get; }\n        public SelectionStrategyAttribute(SelectionMode mode) => Mode = mode;\n    }\n}\n\nnamespace Demo.Contracts\n{\n    public interface ITestService\n    {\n        string Echo(string value);\n    }\n}\n\nnamespace Demo.Contracts.Services.Proxy\n{\n    using Demo.Contracts;\n\n    [RealizeService(typeof(ITestService))]\n    public partial class TestServiceProxy : ITestService\n    {\n        private readonly IRegistry _registry;\n\n        public TestServiceProxy(IRegistry registry)\n        {\n            _registry = registry;\n        }\n\n        // Members will be generated by proxy generator.\n    }\n}\n";

        var syntaxTree = CSharpSyntaxTree.ParseText(source);

        var references = new List<MetadataReference>
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Enumerable).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(List<>).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.IServiceCollection).Assembly.Location)
        };

        var compilation = CSharpCompilation.Create(
            assemblyName: "ProxyGeneratorTestAssembly",
            syntaxTrees: new[] { syntaxTree },
            references: references,
            options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generators = new ISourceGenerator[]
        {
            new ProxyServiceGenerator().AsSourceGenerator(),
            new DIExtensionsGenerator().AsSourceGenerator()
        };

        GeneratorDriver driver = CSharpGeneratorDriver.Create(generators);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        diagnostics.Should().BeEmpty("test input should compile cleanly");

        var runResult = driver.GetRunResult();
        var allGenerated = runResult.Results.SelectMany(r => r.GeneratedSources).ToArray();
        allGenerated.Should().NotBeEmpty();

        var proxySource = allGenerated.Single(s => s.HintName == "TestServiceProxy.g.cs").SourceText.ToString();
        proxySource.Should().Contain("partial class TestServiceProxy : Demo.Contracts.ITestService");
        proxySource.Should().Contain("_registry.Get<Demo.Contracts.ITestService>(PigeonPea.Contracts.Plugin.SelectionMode.HighestPriority)");

        var diSourceEntry = allGenerated.Single(s => s.HintName.EndsWith("ServiceCollectionExtensions.g.cs"));
        var diSource = diSourceEntry.SourceText.ToString();
        diSource.Should().Contain("namespace Demo.Contracts.Services.Extensions;");
        diSource.Should().Contain("public static class ServiceCollectionExtensions");
        diSource.Should().Contain("AddServicesTestServiceProxy");
    }
}
