<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Arch" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\PigeonPea.Shared.Camera2D\PigeonPea.Shared.Camera2D.csproj" />
    <ProjectReference Include="..\..\shared\PigeonPea.Shared\PigeonPea.Shared.csproj" />
  </ItemGroup>

</Project>
