<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\contracts\src\PigeonPea.Map.Contracts\PigeonPea.Map.Contracts.csproj" />
    <ProjectReference Include="..\..\..\core\src\PigeonPea.Map.Encoding\PigeonPea.Map.Encoding.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BruTile.MbTiles" Version="6.0.0" />
    <PackageReference Include="sqlite-net-base" Version="1.10.196-beta" />
    <PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="Dapper" Version="2.1.44" />
  </ItemGroup>

</Project>
